export type ComponentKey =
  | 'welcome'
  | 'user-list'
  | 'user-editor'
  | 'dashboard'

  | 'contratista'
  | 'contratista-list'
  | 'proveedor'
  | 'proveedor-list'
  | 'visitante-list'
  | 'citas-view'
  | 'visitas-list'
  | 'lista-negra'
  | 'lista-negra-list'

  | 'gafete-list'
  | 'ingreso-list'
  | 'ingreso-module'
  | 'general-settings'
  | 'visual-settings'
  | 'update-settings'
  | 'backup-settings'
  | 'device-settings'
  | 'security-settings'
  | 'session-settings'
  | 'export-settings'
  | 'roles-settings'
  | 'reportes-list'
  | 'shortcut-settings'
  | 'about';